@API_HostAddress = http://employee-ms
@API_Port = 8080
@Version = v1
@EmployeeAPI = {{API_HostAddress}}:{{API_Port}}/api/{{Version}}/Employee
@DepartmentAPI = {{API_HostAddress}}:{{API_Port}}/api/{{Version}}/Department
@JobTitleAPI = {{API_HostAddress}}:{{API_Port}}/api/{{Version}}/JobTitle


### 
# @name CreateDepartment
POST {{DepartmentAPI}}
Content-Type: application/json

{
  "Name": "IT",
  "Description": "Information Technology"
}

###
# @name GetDepartments
GET {{DepartmentAPI}}
Content-Type: application/json

###
# @name GetDepartmentById
GET {{DepartmentAPI}}/1
Content-Type: application/json


###
# @name UpdateDepartment
PUT {{DepartmentAPI}}
Content-Type: application/json

{
  "Id": 1,
  "Name": "HR",
  "Description": "Human Resource"
}

###
# @name DeleteDepartment
DELETE {{DepartmentAPI}}/1
Content-Type: application/json

###
# @name CreateJobTitle
POST {{JobTitleAPI}}
Content-Type: application/json

{
  "Name": "Software Engineer",
  "Description": "Software Engineer"
}

###
# @name GetJobTitles
GET {{JobTitleAPI}}
Content-Type: application/json

###
# @name GetJobTitleById
GET {{JobTitleAPI}}/1
Content-Type: application/json

###
# @name UpdateJobTitle
PUT {{JobTitleAPI}}
Content-Type: application/json

{
  "Id": 1,
  "Name": "Senior Software Engineer",
  "Description": "Senior Software Engineer"
}

###
# @name DeleteJobTitle
DELETE {{JobTitleAPI}}/1
Content-Type: application/json

###
# @name CreateEmployee
POST {{EmployeeAPI}}
Content-Type: application/json

{
  "name": "John",
  "surname": "Doe",
  "email": "test@email.com",
  "birthDate": "1985-08-14T08:03:08.782Z",
  "jobTitle": {
    "name": "Software Engineer",
    "description": "Software Engineer"
  },
  "department": {
    "name": "IT",
    "description": "Information Technology"
  },
  "hireDate": "2024-08-14T08:03:08.782Z"
}

