services:
  employee-ms:
    build:
      context: .
      dockerfile: Employee.API/Dockerfile
    container_name: employee-ms
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  
  attendance-ms:
    build:
      context: .
      dockerfile: Attendance.API/Dockerfile
    container_name: attendance-ms
    ports:
      - "8081:8080"
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: MSProd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8000:8080"

volumes:
  postgres_data:
