services:
  employee-ms:
    image: "ghcr.io/classy-giraffe/unims:employee"
    container_name: employee-ms
    ports:
      - "8080:8080"
    depends_on:
      - employee-db
      - kafka
    environment:
      - ConnectionStrings__DefaultConnection=Host=employee-db;Port=5432;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=EmployeeDB;
  
  attendance-ms:
    image: "ghcr.io/classy-giraffe/unims:attendance"
    container_name: attendance-ms
    ports:
      - "8081:8080"
    depends_on:
      - attendance-db
      - employee-ms
    environment:
      - ConnectionStrings__DefaultConnection=Host=attendance-db;Port=5432;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=AttendanceDB;
        
  payroll-ms:
    image: "ghcr.io/classy-giraffe/unims:payroll"
    container_name: payroll-ms
    ports:
      - "8082:8080"
    depends_on:
        - payroll-db
        - employee-ms
    environment:
        - ConnectionStrings__DefaultConnection=Host=payroll-db;Port=5432;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=PayrollDB;
  
  employee-db:
    image: postgres
    container_name: employee-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: EmployeeDB
    volumes:
      - employee-db-data:/var/lib/postgresql/data
  
  attendance-db:
    image: postgres
    container_name: attendance-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: AttendanceDB
    volumes:
      - attendance-db-data:/var/lib/postgresql/data
  
  payroll-db:
    image: postgres
    container_name: payroll-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: PayrollDB
    volumes:
      - payroll-db-data:/var/lib/postgresql/data
  
  zookeeper:
    image: 'bitnami/zookeeper:3.9.0'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper

volumes:
  employee-db-data:
  attendance-db-data:
  payroll-db-data: