name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '43 4 * * *'
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: 'v2.2.4'

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
     - name: Extract Docker metadata for Employee.API
        id: meta_employee
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-employee

      - name: Extract Docker metadata for Attendance.API
        id: meta_attendance
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-attendance

      # Build and push Docker image for Employee.API with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image for Employee.API
        id: build-and-push-employee
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./Employee.API
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_employee.outputs.tags }}
          labels: ${{ steps.meta_employee.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push Docker image for Attendance.API with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image for Attendance.API
        id: build-and-push-attendance
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./Attendance.API
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_attendance.outputs.tags }}
          labels: ${{ steps.meta_attendance.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Sign the resulting Docker image digests except on PRs.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image for Employee.API
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta_employee.outputs.tags }}
          DIGEST: ${{ steps.build-and-push-employee.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      - name: Sign the published Docker image for Attendance.API
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta_attendance.outputs.tags }}
          DIGEST: ${{ steps.build-and-push-attendance.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
